sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t regokan/react-test -f ./react-app/Dockerfile.dev ./react-app

script:
  - docker run -e CI=true regokan/react-test npm run test

after_success:
  - docker build -t regokan/create-react-app ./react-app
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push regokan/create-react-app
